version: "3"
services:
  rules_engine:
    networks:
      - proxy
    read_only: true
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=rules-engine.p.cns.me
        - com.df.port=3002
        - com.df.httpsOnly=true
        - com.df.servicePath=/
        - com.df.xForwardedProto=true
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
    image: pinked/locator
    environment:
      - PEER_DISCOVERY_NAME=rules_engine
      - THRESHOLD=100
      - LATITUDE=${LATITUDE}
      - LONGTITUDE=${LONGTITUDE}
      - SUBSCRIBE=owntracks/*/*
      - USER=${USER}
      - PASS=${PASS}
      - MQTT=${MQTT}

networks:
  proxy:
    external: true