version: "3"
services:
  rules_engine:
    read_only: true
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
    image: pinked/rules_engine:${DRONE_BUILD_NUMBER}
    environment:
      - HANNAH_PROWL_KEY=${HANNAH_PROWL_KEY}
      - CHRIS_PROWL_KEY=${CHRIS_PROWL_KEY}
      - USER=${USER}
      - PASS=${PASS}
      - MQTT=${MQTT}

networks:
  proxy:
    external: true