version: "3"
services:
  rules_engine:
    read_only: true
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.40'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
    image: pinked/rules_engine:${DRONE_BUILD_NUMBER}
    environment:
      - HANNAH_TELEGRAM_ID=${HANNAH_TELEGRAM_ID}
      - CHRIS_TELEGRAM_ID=${CHRIS_TELEGRAM_ID}
      - GROUP_TELEGRAM_ID=${GROUP_TELEGRAM_ID}
      - USER=${USER}
      - PASS=${PASS}
      - MQTT=${MQTT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_IOT_ENDPOINT_HOST=${AWS_IOT_ENDPOINT_HOST}
      - AWS_REGION=${AWS_REGION}

networks:
  proxy:
    external: true
